### ISSUE TITLE
Image assets not loading in Pangolin

### ISSUE THREAD

**Issue by apgapg** [dahliaOS/welcome#3]
**Describe the bug**

Assets like png are loading properly in landing screen when the project is run as standalone flutter app. The issue is due to `package` parameter passed in `Image.asset` widget. Although this is required to use assets packages but we need to somehow also make them run when running as a separate app. 

**What kind of a bug is it?**
Visual 

**To Reproduce**
Simply run the app by cloning it. I have used Linux as host for running flutter app

**Expected behavior**

Assets should load properly

# Suggestion

Can we add `isDebug` check to `package` parameter to supply package name only when in production mode? Currently I am not aware how debug mode behave on dahila os as I am running this on Linux Ubuntu.

**Comment by SincerelyFaust** [comment]
Has this occured on the main branch?

**Comment by apgapg** [comment]
Yes, on main branch.
looks like i completely miss the `dev` branch ;)

**Comment by apgapg** [comment]
`dev` branch works fine. Looks like image.asset not used anymore

**Comment by SincerelyFaust** [comment]
Image assets are not being loaded in Pangolin but they are in the standalone app, we should:
1. Add `package` parameter to `Image.asset`
2. Add `isDebug` check to supply package name only in production mode

**Comment by apgapg** [comment]
I shall pick this thing. Will report back with a PR by tomorrow

**Comment by SincerelyFaust** [comment]
Fixed by #10
